update=03.04.2019 7:54:35
last_client=kicad
[general]
version=1
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
LabSize=60
[eeschema]
version=1
LibDir=D:/usr/KiCad/Data/library;D:/usr/KiCad/Data/template
[eeschema/libraries]
LibName1=C:/usr/KiCad4/Data/kicad/library/power
